### PR TITLE
Night mode style

### PR DESCRIPTION
**Pull request by virenvshah**
This PR adds the following:
1. Night Mode styling to the WebGUI.
2. An initial draft of a manual test case list.
3. General code cleanup + comments
4. Bug fixes (such as Python programs not terminating properly, some Ports not working properly, Blockly code vanishing when changing tabs) 

From now on make sure the manual test suite is run by every PR owner before they merge their PR into master!  Hopefully over the next few semesters we can try automating some of these tests.

### CODE REVIEW

**Review by ruiqizhu26 — COMMENTED** [review]
Thanks for catching bad requests!

**Review by ruiqizhu26 — COMMENTED** [review]
Thanks for cleaning up the python error message code! This is much structured than before

**Review by ruiqizhu26 — APPROVED** [review]
Thanks for the test suite manual! This can definitely help members to get familiar with projects they didn't work on

**Review by kabirwalia8300 — APPROVED** [review]
Thanks for this 💯

**Review by slawrence100 — APPROVED** [review]
Good work!

**Pull request merged**
