### PR TITLE
Style guides

### PR DESCRIPTION
**Pull request by virenvshah**
Added a Python and React style guide for team members to refer to before submitting a Pull Request

### CODE REVIEW

**Review by tl676 — DISMISSED** [review]

**Review by kabirwalia8300 — DISMISSED** [review]
Looks good!

**Review by slawrence100 — COMMENTED** [review]
Looks like a good starting point! The only thing I wanted to comment on was a styling rule for promises / callbacks - the indentation can get confusing to me sometimes with the `.then`s and the double-braces (`({`, `})`), so I usually refer to [Mozlla's examples (not an actual style guide)](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Using_promises), but with arrow functions when possible:
```js
doSomethingAsynchronously()
.then((arg1, arg2) => {
  // do things here with arg1 and arg2
})
.catch( (err) => console.log("Oops"))
```
All of the above is more or less my personal taste. Either way, do you (or anyone on the team, for that matter) think we should have a convention for this?

**Review by greg1002 — DISMISSED** [review]
Look really good! One thing I would suggest is adding styling guidelines with indentation in react, but only if you think it's necessary. For example, for the sake of clarity, we want:
```javascript
{
  property1: value1,
  property2: value2,
  ...
}
```
```html
<ReactObject
  props1=value1
  props2=value2
  ...
\>
```
If there are too many properties/props, we don't want
```javascript
{ property1: value1, property2: value2, ... }
```
```html
<ReactObject props1=value1 props2=values2 ... \>
```

**Review by SwathiParthibha — APPROVED** [review]

**Comment by virenvshah** [comment]
Thanks for the comments!  I'll incorporate that and merge the PR!

**Comment by virenvshah** [comment]
Ah crap, you all have to reapprove it since I made changes :(

**Review by greg1002 — APPROVED** [review]

**Review by JessieWang0706 — APPROVED** [review]

**Review by slawrence100 — APPROVED** [review]

**Pull request merged**
