### PR TITLE
Updated basestation/requirements.txt

### PR DESCRIPTION
**Pull request by ruiqizhu26**
Change to the followings:
cffi==1.14.5
SpeechRecognition==3.8.1

### CODE REVIEW

**Review by kabirwalia8300 — APPROVED** [review]
Awesome!

**Review by slawrence100 — APPROVED** [review]
Looks good - Thanks!

**Comment by swathi-parthibha** [comment]
looks good!

**Review by swathi-parthibha — APPROVED** [review]
looks good!

**Pull request merged**
