### PR TITLE
Chatbot 

### PR DESCRIPTION
**Pull request by DoanhTran**
Chatbot merged to master.

### CODE REVIEW

**Comment by LinJing-Liu** [comment]
good to merge!

**Review by LinJing-Liu — APPROVED** [review]
good to merge!

**Review by emz1003 — COMMENTED** [review]
Not sure if it's just me, but I wasn't able to sign in/log in on basestation for this branch

**Review by emz1003 — APPROVED** [review]
Looks good to me!

**Review by kchiem12 — APPROVED** [review]
looks good to me

**Pull request merged**
